#!/bin/bash
set -e

NUMBER_OF_PROCESSORS=$(nproc --all)
cmake -B build-paho -S . -DIMQTT_USE_PAHO:BOOL=ON -DIMQTT_BUILD_SAMPLE:BOOL=ON -DIMQTT_INSTALL:BOOL=OFF -DIMQTT_BUILD_DOC:BOOL=OFF -DBUILD_SHARED_LIBS=OFF
cmake --build build-paho -j ${NUMBER_OF_PROCESSORS}

cmake -B build-mosq -S . -DIMQTT_USE_MOSQ:BOOL=ON -DIMQTT_BUILD_SAMPLE:BOOL=ON -DIMQTT_INSTALL:BOOL=OFF -DIMQTT_BUILD_DOC:BOOL=OFF -DBUILD_SHARED_LIBS=OFF
cmake --build build-mosq -j ${NUMBER_OF_PROCESSORS}